apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: igc-golang
  labels:
    version: 1.24.0
spec:
  resources:
    - name: git-source
      type: git
    - name: docker-image
      type: image
  tasks:
    - name: test
      taskRef:
        name: igc-golang-test-v1-24-0
      resources:
        inputs:
          - name: source
            resource: git-source
    - name: build
      taskRef:
        name: igc-build-tag-push-v1-24-0
      runAfter:
       - test
      resources:
        inputs:
          - name: source
            resource: git-source
        outputs:
          - name: image
            resource: docker-image
    - name: deploy
      taskRef:
        name: igc-deploy-v1-24-0
      runAfter:
       - build
      resources:
        inputs:
          - name: source
            resource: git-source
          - name: image
            resource: docker-image
    - name: health
      taskRef:
        name: igc-health-check-v1-24-0
      runAfter:
       - deploy
      resources:
        inputs:
          - name: source
            resource: git-source
          - name: image
            resource: docker-image
    - name: release
      taskRef:
        name: igc-helm-package-v1-24-0
      runAfter:
       - health
      resources:
        inputs:
          - name: source
            resource: git-source
          - name: image
            resource: docker-image
    - name: gitops
      taskRef:
        name: igc-gitops-edge-v1-24-0
      runAfter:
       - release
      resources:
        inputs:
          - name: source
            resource: git-source
          - name: image
            resource: docker-image
