apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: igc-golang-test
  labels:
    version: 1.24.0
spec:
  resources:
    - name: git-source
      type: git
    - name: docker-image
      type: image
  tasks:
    - name: health
      taskRef:
        name: igc-health-check-v1-24-0
      resources:
        inputs:
          - name: source
            resource: git-source
          - name: image
            resource: docker-image
    - name: edge-cd
      taskRef:
        name: igc-gitops-edge-v1-24-0
      runAfter:
       - health
      resources:
        inputs:
          - name: source
            resource: git-source
          - name: image
            resource: docker-image
